Drop unnecessary lines from Dockerfile
/workspace does not exist in the container image and building the image
fails with the following error.

[2/2] STEP 13/19: COPY --from=builder /workspace/manager .
Error: building at STEP "COPY --from=builder /workspace/manager .":
checking on sources under "...": copier: stat: "/workspace/manager":
no such file or directory

The file should be copied into $DEST_ROOT instead.

Also, user is already twice and the second definition looks redundant.